### ISSUE TITLE
smaller and faster than GSAP

### ISSUE THREAD

**Issue by leeoniya** [phaserjs/phaser-nano#2]
@photonstorm 

supposedly faster than GSAP:

https://github.com/nextapps-de/fat#benchmark-ranking

not sure how contrived the bench is, but seems true on my machine:

https://nextapps-de.github.io/fat/

**Comment by photonstorm** [comment]
Thanks for the heads-up. I'd never include gsap with Phaser anyway, was just using it for some dirty tests before I swap to something less hungry. But this does look quite nice, even if the code structure is a little odd!
