### ISSUE TITLE
Layers

### ISSUE THREAD

**Issue by PhaserEditor2D** [phaserjs/phaser-nano#3]
I think I read in an early Phaser 3 development log, or maybe in Lazer,  about object layers. I think it is something that can be added to Phaser 4. We can simulate a layer with a container, but maybe a layer could be more performing if it is dedicated only to sort the rendering order of the objects, without the transformation stuff.

Probably in Phaser 3 we can layer objects using different depths, but a layer could be more friendly. Something like:

```javascript

// const sky = this.add.layer();
const sky = new Layer(this);
sky.add(cloud1);
sky.add(cloud2);

// or this way too:

new Layer(this, cloud1, cloud2);

```

**Comment by photonstorm** [comment]
So the only difference between this and a Container is that Layer doesn't have x, y, scale, etc? Meaning that all it would do is iterate through its children - and you'd be able to set visible false to the whole thing, too.

**Comment by PhaserEditor2D** [comment]
Yes, it is just about the rendering order of the objects.

**Comment by PhaserEditor2D** [comment]
I think this was implemented in Phaser 4.
